//! Wormhole reference data, bundled: every hole type with where it can spawn, where it leads, its
//! mass and lifetime; every J-space system's class, effect and statics; the effect modifiers per
//! class; and which k-space systems can spawn which Pochven system's C729. Generated by
//! `tools/gen_whdata.py` from anoik.is, Jambeeno (CC BY 4.0) and the CCP SDE.

use std::collections::HashMap;
use std::sync::LazyLock;

static DATA_GZ: &[u8] = include_bytes!("../assets/whdata.json.gz");

pub const ATTRIBUTION: &str =
    "Wormhole data: anoik.is; Pochven C729 zones: Jambeeno (jambeeno.com), CC BY 4.0; CCP SDE.";

/// What sort of space a system is, as far as wormholes care.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Class {
    /// C1 to C6, and 13 for the shattered frigate systems.
    W(u8),
    Hs,
    Ls,
    Ns,
    Thera,
    /// Sentinel, Barbican, Vidette, Conflux, Redoubt: classes 14 to 18.
    Drifter(u8),
    Pochven,
    Turnur,
    Tabbetzur,
}

impl Class {
    fn parse(s: &str) -> Option<Class> {
        Some(match s {
            "hs" => Class::Hs,
            "ls" => Class::Ls,
            "ns" => Class::Ns,
            "thera" => Class::Thera,
            "pochven" => Class::Pochven,
            "turnur" => Class::Turnur,
            "tabbetzur" => Class::Tabbetzur,
            "sentinel" => Class::Drifter(14),
            "barbican" => Class::Drifter(15),
            "vidette" => Class::Drifter(16),
            "conflux" => Class::Drifter(17),
            "redoubt" => Class::Drifter(18),
            c => Class::W(c.strip_prefix('c')?.parse().ok()?),
        })
    }

    pub fn is_kspace(self) -> bool {
        matches!(self, Class::Hs | Class::Ls | Class::Ns | Class::Pochven | Class::Turnur | Class::Tabbetzur)
    }

    pub fn label(self) -> String {
        match self {
            Class::W(13) => "C13 (shattered)".into(),
            Class::W(n) => format!("C{n}"),
            Class::Hs => "Highsec".into(),
            Class::Ls => "Lowsec".into(),
            Class::Ns => "Nullsec".into(),
            Class::Thera => "Thera".into(),
            Class::Drifter(14) => "Sentinel (Drifter)".into(),
            Class::Drifter(15) => "Barbican (Drifter)".into(),
            Class::Drifter(16) => "Vidette (Drifter)".into(),
            Class::Drifter(17) => "Conflux (Drifter)".into(),
            Class::Drifter(_) => "Redoubt (Drifter)".into(),
            Class::Pochven => "Pochven".into(),
            Class::Turnur => "Turnur".into(),
            Class::Tabbetzur => "Tabbetzur".into(),
        }
    }

    /// The class tier an effect's strength is read at: C13 at C6 strength, Drifter systems at C2.
    fn effect_tier(self) -> Option<usize> {
        match self {
            Class::W(13) => Some(5),
            Class::W(n @ 1..=6) => Some(n as usize - 1),
            Class::Drifter(_) => Some(1),
            _ => None,
        }
    }
}

/// Where a hole may lead: one class, or any k-space band (the C729's far side).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dest {
    Class(Class),
    AnyKspace,
    /// K162: the far side's type decides.
    Unknown,
}

#[derive(Clone, Debug)]
pub struct HoleType {
    pub code: String,
    pub src: Vec<Class>,
    pub dest: Dest,
    pub is_static: bool,
    pub lifetime_h: f32,
    pub total_mass: u64,
    pub jump_mass: u64,
}

impl HoleType {
    fn leads_to(&self, c: Class) -> bool {
        match self.dest {
            Dest::Class(d) => d == c,
            Dest::AnyKspace => matches!(c, Class::Hs | Class::Ls | Class::Ns),
            Dest::Unknown => false,
        }
    }

    /// The hole's size class by jump mass. A 1,000,000 t XL takes freighters but no capitals;
    /// the bigger ones do.
    pub fn size_label(&self) -> &'static str {
        match self.jump_mass {
            0 => "any",
            m if m <= 5_000_000 => "Small",
            m if m <= 62_000_000 => "Medium",
            m if m <= 410_000_000 => "Large",
            m if m <= 1_000_000_000 => "XL",
            _ => "XL (capitals)",
        }
    }
}

#[derive(Clone, Debug)]
pub struct JSystem {
    pub class: Class,
    pub effect: Option<String>,
    pub statics: Vec<String>,
    /// e.g. "K7 (Orange)".
    pub sun: String,
    /// Each planet's kind, e.g. "Barren", in orbit order.
    pub planets: Vec<String>,
    pub moons: u32,
}

impl JSystem {
    pub fn shattered(&self) -> bool {
        self.planets.iter().any(|p| p == "Shattered")
    }
}

struct Data {
    types: Vec<HoleType>,
    systems: HashMap<i64, JSystem>,
    /// Effect name -> modifier name -> strength per class tier (C1..C6).
    effects: HashMap<String, Vec<(String, Vec<String>)>>,
    /// k-space system name (lowercase) -> the Pochven systems whose C729 it can host.
    c729: HashMap<String, Vec<String>>,
}

#[derive(serde::Deserialize)]
struct RawType {
    code: String,
    src: Vec<String>,
    dest: String,
    #[serde(rename = "static")]
    is_static: bool,
    lifetime_h: f32,
    total_mass: u64,
    jump_mass: u64,
}

#[derive(serde::Deserialize)]
struct Raw {
    types: Vec<RawType>,
    systems: Vec<(i64, String, Option<String>, Vec<String>, String, Vec<String>, u32)>,
    effects: HashMap<String, HashMap<String, Vec<String>>>,
    c729: Vec<(String, Vec<String>)>,
}

static DATA: LazyLock<Data> = LazyLock::new(load);

fn load() -> Data {
    use std::io::Read;
    let mut text = String::new();
    let raw: Option<Raw> = flate2::read::GzDecoder::new(DATA_GZ)
        .read_to_string(&mut text)
        .ok()
        .and_then(|_| serde_json::from_str(&text).ok());
    let Some(raw) = raw else {
        return Data { types: Vec::new(), systems: HashMap::new(), effects: HashMap::new(), c729: HashMap::new() };
    };
    let types = raw
        .types
        .into_iter()
        .map(|t| HoleType {
            dest: match t.dest.as_str() {
                "ks" => Dest::AnyKspace,
                d => Class::parse(d).map_or(Dest::Unknown, Dest::Class),
            },
            src: t.src.iter().filter_map(|s| Class::parse(s)).collect(),
            code: t.code,
            is_static: t.is_static,
            lifetime_h: t.lifetime_h,
            total_mass: t.total_mass,
            jump_mass: t.jump_mass,
        })
        .collect();
    let systems = raw
        .systems
        .into_iter()
        .filter_map(|(id, class, effect, statics, sun, planets, moons)| {
            Some((id, JSystem { class: Class::parse(&class)?, effect, statics, sun, planets, moons }))
        })
        .collect();
    let effects = raw
        .effects
        .into_iter()
        .map(|(name, mods)| {
            let mut mods: Vec<(String, Vec<String>)> = mods.into_iter().collect();
            mods.sort();
            (name, mods)
        })
        .collect();
    let c729 = raw.c729.into_iter().map(|(sys, to)| (sys.to_lowercase(), to)).collect();
    Data { types, systems, effects, c729 }
}

pub fn hole_type(code: &str) -> Option<&'static HoleType> {
    DATA.types.iter().find(|t| t.code.eq_ignore_ascii_case(code.trim()))
}

pub fn types() -> &'static [HoleType] {
    &DATA.types
}

pub fn jsystem(id: i64) -> Option<&'static JSystem> {
    DATA.systems.get(&id)
}

/// What an effect means for a fight, in a sentence.
pub fn effect_summary(effect: &str) -> &'static str {
    match effect {
        "Magnetar" => "Every weapon and drone hits harder, but tracking, missile application and targeting range suffer. Favours close-range brawling against big targets.",
        "Black Hole" => "Ships fly faster but turn slower, missiles fly faster, webs are weaker and targeting range is longer. Tackle is hard to hold; favours fast and kiting ships.",
        "Pulsar" => "More shield HP and faster capacitor recharge, weaker armor resists, bigger signatures and stronger neuts. Favours shield ships, hurts armor ones.",
        "Wolf-Rayet Star" => "More armor HP and small weapon damage, weaker shield resists, smaller signatures. Favours armor ships and small hulls.",
        "Cataclysmic Variable" => "Remote repairs are stronger, local repairs weaker, more capacitor but slower recharge and weaker remote cap. Favours remote-repair fleets.",
        "Red Giant" => "Overheating gives more and burns modules faster; smartbombs and bombs hit harder and reach further.",
        _ => "",
    }
}

/// What kind of place a class is, in a sentence.
pub fn class_summary(class: Class) -> &'static str {
    match class {
        Class::W(1) => "Class 1: the easiest sites, and every hole into it takes medium hulls at most.",
        Class::W(2) => "Class 2: easy sites and two statics, one to k-space and one to J-space.",
        Class::W(3) => "Class 3: moderate sites and one k-space static; common for solo and small-gang ratting.",
        Class::W(4) => "Class 4: two J-space statics and no k-space static, so it is hard to reach from k-space.",
        Class::W(5) => "Class 5: hard sites run with capitals or large fleets; usually lived in by big groups.",
        Class::W(6) => "Class 6: the hardest sites and the largest groups; capital escalations.",
        Class::W(13) => "Shattered frigate hole system: only frigate-size ships fit through its holes.",
        Class::Thera => "Thera: a hub with many holes to k-space and NPC stations, mapped by EVE-Scout.",
        Class::Drifter(_) => "Drifter system: reached through the holes by Jove observatories, guarded by Drifters.",
        Class::Turnur => "Turnur: lowsec hub that holes from C1 to C4 can lead to.",
        Class::Pochven => "Pochven: Triglavian space, reached by its own C729 holes and filaments.",
        _ => "",
    }
}

pub const SHATTERED_NOTE: &str = "Shattered: no moons, richer ore and gas sites, and no Upwell structures can be anchored.";

/// The five drifter systems: class number, the name intel uses, system id.
pub const DRIFTERS: [(u8, &str, i64); 5] = [
    (14, "sentinel", 31_000_001),
    (15, "barbican", 31_000_002),
    (16, "vidette", 31_000_003),
    (17, "conflux", 31_000_004),
    (18, "redoubt", 31_000_006),
];

/// The drifter system a hole type leads to: B735 to Barbican and so on.
pub fn drifter_for_code(code: &str) -> Option<i64> {
    match hole_type(code)?.dest {
        Dest::Class(Class::Drifter(n)) => DRIFTERS.iter().find(|d| d.0 == n).map(|d| d.2),
        _ => None,
    }
}

/// The drifter system a message names, as a whole word.
pub fn drifter_in_text(text: &str) -> Option<i64> {
    let words: Vec<String> = text.split(|c: char| !c.is_alphanumeric()).map(str::to_lowercase).collect();
    DRIFTERS.iter().find(|d| words.iter().any(|w| w == d.1)).map(|d| d.2)
}

/// An effect's modifiers at a system's strength, e.g. ("Armor HP", "+44%").
pub fn effect_mods(effect: &str, class: Class) -> Vec<(String, String)> {
    let (Some(mods), Some(tier)) = (DATA.effects.get(effect), class.effect_tier()) else { return Vec::new() };
    mods.iter().filter_map(|(m, per)| Some((m.clone(), per.get(tier)?.clone()))).collect()
}

/// The Pochven systems whose C729 can spawn in k-space system `name`.
pub fn c729_targets(name: &str) -> &'static [String] {
    DATA.c729.get(&name.to_lowercase()).map_or(&[], Vec::as_slice)
}

/// The k-space systems that can host Pochven system `pochven`'s C729.
pub fn c729_zone(pochven: &str) -> Vec<&'static str> {
    let mut out: Vec<&str> = DATA
        .c729
        .iter()
        .filter(|(_, to)| to.iter().any(|p| p.eq_ignore_ascii_case(pochven)))
        .map(|(k, _)| k.as_str())
        .collect();
    out.sort_unstable();
    out
}

pub const THERA: i64 = 31_000_005;
pub const TURNUR: i64 = 30_002_086;
pub const TABBETZUR: i64 = 30_003_465;

/// The class of system `id`, `security` and `region` as the SDE has them.
pub fn class_of(id: i64, security: f64, region: &str) -> Class {
    if id == THERA {
        return Class::Thera;
    }
    if id == TURNUR {
        return Class::Turnur;
    }
    if id == TABBETZUR {
        return Class::Tabbetzur;
    }
    if let Some(j) = jsystem(id) {
        return j.class;
    }
    if region.eq_ignore_ascii_case("Pochven") {
        return Class::Pochven;
    }
    // Highsec is read rounded (0.45 is highsec); anything above zero at all is lowsec.
    if (security * 10.0).round() / 10.0 >= 0.5 {
        Class::Hs
    } else if security > 0.0 {
        Class::Ls
    } else {
        Class::Ns
    }
}

/// Turnur and Tabbetzur are lowsec for the holes that spawn there (B449, N944, S199 and the like).
fn as_band(c: Class) -> Class {
    match c {
        Class::Turnur | Class::Tabbetzur => Class::Ls,
        c => c,
    }
}

/// A hole type that could have carried a pilot from `from` to `to`, and which side it was on: the
/// type itself in `from`, or its K162 in `from` with the type in `to`.
#[derive(Clone, Debug, PartialEq)]
pub struct Candidate {
    pub code: &'static str,
    /// True when the named type was in `to` and `from` held its K162.
    pub reverse: bool,
}

/// The one hole that most likely carried a pilot from system `from` to `to`: the only candidate,
/// else the only one that is a static of the J-system it would sit in.
pub fn likely_hole(from: i64, to: i64, cands: &[Candidate]) -> Option<Candidate> {
    if let [only] = cands {
        return Some(only.clone());
    }
    let statics = |id: i64| jsystem(id).map(|j| j.statics.as_slice()).unwrap_or_default();
    let fits: Vec<&Candidate> = cands
        .iter()
        .filter(|c| statics(if c.reverse { to } else { from }).iter().any(|s| s == c.code))
        .collect();
    match fits.as_slice() {
        [only] => Some((*only).clone()),
        _ => None,
    }
}

/// Every hole type able to connect `from` to `to`, either way round.
pub fn possible_holes(from: Class, to: Class) -> Vec<Candidate> {
    let mut out = Vec::new();
    for t in &DATA.types {
        let src_has = |c: Class| t.src.contains(&c) || t.src.contains(&as_band(c));
        let leads = |c: Class| t.leads_to(c) || t.leads_to(as_band(c));
        if src_has(from) && leads(to) {
            out.push(Candidate { code: t.code.as_str(), reverse: false });
        }
        if src_has(to) && leads(from) {
            out.push(Candidate { code: t.code.as_str(), reverse: true });
        }
    }
    out
}

#[cfg(test)]
mod tests {

    #[test]
    fn a_drifter_hole_is_placed_by_its_code_or_by_name() {
        assert_eq!(drifter_for_code("B735"), Some(31_000_002));
        assert_eq!(drifter_for_code("V928"), Some(31_000_003));
        assert_eq!(drifter_for_code("K162"), None);
        assert_eq!(drifter_in_text("barbican hole in 1DQ1-A"), Some(31_000_002));
        assert_eq!(drifter_in_text("Redoubt, 4 jumps"), Some(31_000_006));
        assert_eq!(drifter_in_text("sentinels on gate"), None, "whole words only");
    }

    use super::*;

    #[test]
    fn a_static_out_of_the_j_system_is_the_likely_hole() {
        // J111613 is a C5 with an E175 static to C4; a K162 in some C4 ...
        let j = 31_002_318;
        let cands = possible_holes(Class::W(5), Class::W(4));
        assert!(cands.len() > 1, "{cands:?}");
        let pick = likely_hole(j, 99, &cands).expect("the static");
        assert_eq!((pick.code, pick.reverse), ("E175", false));
        // ... and coming the other way, the same static seen from its K162.
        let back = possible_holes(Class::W(4), Class::W(5));
        let pick = likely_hole(99, j, &back).expect("the static, reversed");
        assert_eq!((pick.code, pick.reverse), ("E175", true));
    }

    #[test]
    fn the_bundle_loads_and_covers_what_the_parser_knows() {
        assert!(types().len() >= 100);
        for w in crate::wormholes::WH_TYPES {
            assert!(hole_type(w.0).is_some(), "{} is in the parser's list but not the data", w.0);
        }
        let c247 = hole_type("C247").expect("C247");
        assert_eq!(c247.src, vec![Class::W(4)]);
        assert_eq!(c247.dest, Dest::Class(Class::W(3)));
        assert_eq!(hole_type("c729").map(|t| t.dest), Some(Dest::AnyKspace));
    }

    #[test]
    fn systems_have_class_effect_and_statics() {
        let thera = jsystem(THERA).expect("Thera");
        assert_eq!(thera.class, Class::Thera);
        let sentinel = jsystem(31_000_001).expect("Sentinel");
        assert_eq!(sentinel.class, Class::Drifter(14));
        assert!(DATA.systems.len() > 2500);
        let some_c5 = DATA.systems.values().find(|s| s.class == Class::W(5) && s.effect.is_some()).expect("a C5 with an effect");
        assert!(!effect_mods(some_c5.effect.as_deref().unwrap(), Class::W(5)).is_empty());
    }

    #[test]
    fn pochven_zones_read_both_ways() {
        assert!(c729_targets("Isanamo").iter().any(|p| p == "Kino"));
        assert!(c729_zone("Kino").contains(&"isanamo"));
        assert!(c729_targets("Jita").is_empty());
    }

    #[test]
    fn classes_by_security_band() {
        assert_eq!(class_of(30_000_142, 0.946, "The Forge"), Class::Hs);
        assert_eq!(class_of(1, 0.45, "X"), Class::Hs);
        assert_eq!(class_of(1, 0.44, "X"), Class::Ls);
        assert_eq!(class_of(1, 0.04, "X"), Class::Ls);
        assert_eq!(class_of(1, -0.2, "X"), Class::Ns);
        assert_eq!(class_of(30_001_372, -1.0, "Pochven"), Class::Pochven);
        assert_eq!(class_of(TURNUR, 0.39, "Metropolis"), Class::Turnur);
    }

    #[test]
    fn which_holes_can_connect_two_classes() {
        let codes = |a, b| possible_holes(a, b).into_iter().map(|c| (c.code, c.reverse)).collect::<Vec<_>>();
        assert!(codes(Class::Ns, Class::Ns).contains(&("S199", false)), "S199 nullsec to nullsec");
        assert!(codes(Class::W(4), Class::W(3)).contains(&("C247", false)));
        assert!(codes(Class::W(3), Class::W(4)).contains(&("C247", true)), "the K162 of a C4's C247");
        assert!(codes(Class::Pochven, Class::Hs).contains(&("C729", false)));
        assert!(codes(Class::Hs, Class::Pochven).contains(&("C729", true)));
        assert!(codes(Class::Hs, Class::Hs).contains(&("A641", false)));
        assert!(!codes(Class::W(1), Class::Ls).is_empty());
    }
}
